name: Code Quality

on:
  push:
    paths:
      - 'assets/js/**/*.js'
  pull_request:
    paths:
      - 'assets/js/**/*.js'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint
        run: npx eslint assets/js --ext .js 